// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWOLT7wLjDIv7h4zx8fmaAne324Xd8gNQ',
    appId: '1:484577127036:web:9f4a09002f04ed7832b7f9',
    messagingSenderId: '484577127036',
    projectId: 'fir-shop-a37fb',
    authDomain: 'fir-shop-a37fb.firebaseapp.com',
    storageBucket: 'fir-shop-a37fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkZaAnugVNuWAbdzTWPaWA2W2XQbo9Jk',
    appId: '1:484577127036:android:f3f04571712f685c32b7f9',
    messagingSenderId: '484577127036',
    projectId: 'fir-shop-a37fb',
    storageBucket: 'fir-shop-a37fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcX-w09UXhc74vVxoZNS_QeRv3XtNPlq4',
    appId: '1:484577127036:ios:dd2a4e669c434ee932b7f9',
    messagingSenderId: '484577127036',
    projectId: 'fir-shop-a37fb',
    storageBucket: 'fir-shop-a37fb.firebasestorage.app',
    iosBundleId: 'com.example.shopAgence',
  );
}
